version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

# TODO Add support for maven dependencies once a manual review of dependencies has been made.