remote_theme: jakartaee/jekyll-theme-jakarta-ee

title: [Jakarta JSON Binding]
description: [Homepage for resources related to the Jakarta JSON Binding project]

# sidebar links url
# TODO update links to point to snapshot version of javadoc / userguide / tck guide
links:
  source: https://github.com/jakartaee/jsonb-api
  download: https://github.com/jakartaee/jsonb-api/releases
  hide_issuetracker: true # Issue tracker never populates correctly
  mailinglist: https://accounts.eclipse.org/mailing-list/jsonb-dev
  javadocs: SNAPSHOT/api/apidocs/
  docs: SNAPSHOT/docs/
  faq: SNAPSHOT/tck/

