== Executing Tests

The {TechnologyShortName} TCK uses the Junit 
framework to execute the tests.

This chapter includes the following topics:

* <<Starting the tests>>
* <<Running a Subset of the Tests>>
* <<Running the TCK Against another CI>>
* <<Running the TCK Against a Vendor Implementation>>
* <<Test Reports>>


[NOTE]
=======================================================================

The instructions in this chapter assume that you have installed and
configured your test environment as described in
<<Installation>> and <<Setup and Configuration>>
respectively.

=======================================================================

ifdef::rebuild[]
As explained in link:rebuild.html#GCLIZ[Appendix B, "Packaging the
Test Applications in Servlet-Compliant WAR
Files With VI-Specific Information,"] the {TechnologyShortName} TCK
introduces the concept of repackaging the TCK tests.
endif::rebuild[]

=== Starting the tests

The {TechnologyShortName} TCK can be run from the command line 
in your shell environment by executing tests from the TCK jar.

[NOTE]
=======================================================================

The `mvn` command referenced in the following
two procedures and elsewhere in this guide is the Apache Maven
build tool, which will need to be downloaded separately.

=======================================================================

==== To Run All Tests

To run all tests, enter the following command:

[source,subs="attributes"]
----
cd ${TechnologyHomeEnv}/bin
mvn verify
----

=== Running a Subset of the Tests

Use the following modes to run a subset of the tests:

* <<To Run a Single Test>>
* <<To Run a Subset of Tests>>
* <<To Run Signature Tests>>

==== To Run a Single Test

To run a single test, enter the following command: +

[source,subs="attributes"]
----
cd ${TechnologyHomeEnv}/bin
mvn verify -Dtest={singleTestExample}
----

==== To Run a Subset of Tests

To run a subset of tests, enter the following command:

[source,subs="attributes"]
----
cd ${TechnologyHomeEnv}/bin
mvn verify -Dtest={subsetTestDirectoryExample}
----

==== To Run Signature Tests

To run the {TechnologyShortName} TCK Signature Tests, enter the
following command:

[source,subs="attributes"]
----
cd ${TechnologyHomeEnv}/bin
mvn verify -Dtest={sigTestExample}
----

=== Running the TCK Against another CI

Some test scenarios are designed to ensure that the configuration and deployment of
all the prebuilt {TechnologyShortName} TCK tests against one Compatible
Implementation are successful operating with other compatible implementations, and that the TCK is ready for
compatibility testing against the Vendor and Compatible Implementations.

1.  Verify that you have followed the configuration instructions in
<<Configuring Your Environment to Run the TCK Against the Reference Implementation>>.
2.  Run the tests, as described in <<Starting the tests>> and, 
if desired, <<Running a Subset of the Tests>>.

=== Running the TCK Against a Vendor Implementation

This test scenario is one of the compatibility test phases that all
Vendors must pass.

1.  Verify that you have followed the configuration instructions in
<<Configuring Your Environment to Run the TCK Against the Vendor Implementation>>.
2.  Run the tests, as described in <<Starting the tests>> and, if desired, <<Running a Subset of the Tests>>.

=== Test Reports

A set of report files is created for every test run. These report files
can be found in the target directory that the test is run. After a test run is
completed, the Junit framework writes  reports for the test run.
