#
# Copyright (c) 2026 Eclipse Foundation and/or its affiliates. All rights reserved.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v. 2.0, which is available at
# http://www.eclipse.org/legal/epl-2.0.
#
# This Source Code may also be made available under the following Secondary
# Licenses when the conditions for such availability set forth in the
# Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
# version 2 with the GNU Classpath Exception, which is available at
# https://www.gnu.org/software/classpath/license.html.
#
# SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
#

# This workflow is triggered on push to the default branch and on release published events.
# It is used to build the documentation for the project, and update the github pages branch with the generated documentation.
# This will include the following:
# - The user guide (docs/target/generated-docs/user-guide.html)
# - The API Javadoc (api/target/apidocs/)
# - The TCK guide (tck-dist/target/jsonb-tck-reference-guide.html)

name: Documentation

on:
  push:
    branches:
      - 'main'
    paths: # Limit rebuilding the site to only when the following directories are changed.
      - 'docs/src/**'
      - 'api/src/**'
      - 'tck-dist/src/**'
  release:
    types: [published]
  workflow_dispatch: #For testing purposes

# pages: write and id-token: write are required by actions/deploy-pages.
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Set up JDK 17
      uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build documentation
      run: mvn -B clean package -DskipTests -Prelease
    - name: Determine target subdirectory
      id: target_dir
      run: |
        if [ "${{ github.event_name }}" = "release" ]; then
          echo "subdir=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
        else
          echo "subdir=SNAPSHOT" >> $GITHUB_OUTPUT
        fi
    - name: Assemble documentation
      run: |
        mkdir -p "_site/docs"
        mkdir -p "_site/api"
        mkdir -p "_site/tck"

        cp README.md "_site/README.md"
        cp docs/target/generated-docs/user-guide.html "_site/docs/index.html"
        cp -r api/target/apidocs/ "_site/api/"
        cp tck-dist/target/generated-docs/jsonb-tck-reference-guide.html "_site/tck/index.html"
    - name: Deploy to GitHub Pages
      uses: jamesives/github-pages-deploy-action@fa24774553152dd7873cd16ebd8d959b010c5445 # v4.9.0
      with:
        folder: _site
        branch: gh-pages
        target-folder: ${{ steps.target_dir.outputs.subdir }}
